# Generated by Django 6.0.3 on 2026-06-13 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usuario", models.CharField(max_length=50, unique=True)),
                ("nombre", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
                (
                    "rol",
                    models.CharField(
                        choices=[
                            ("Administrador", "Administrador"),
                            ("Empleado", "Empleado"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="producto",
            name="codigo",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="producto",
            name="precio",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="producto",
            name="stock",
            field=models.IntegerField(default=0),
        ),
    ]
